# start of generated code
	.data
	.align	2
	.globl	class_nameTab
	.globl	Main_protObj
	.globl	Int_protObj
	.globl	String_protObj
	.globl	bool_const0
	.globl	bool_const1
	.globl	_int_tag
	.globl	_bool_tag
	.globl	_string_tag
_int_tag:
	.word	10
_bool_tag:
	.word	11
_string_tag:
	.word	12
	.globl	_MemMgr_INITIALIZER
_MemMgr_INITIALIZER:
	.word	_GenGC_Init
	.globl	_MemMgr_COLLECTOR
_MemMgr_COLLECTOR:
	.word	_GenGC_Collect
	.globl	_MemMgr_TEST
_MemMgr_TEST:
	.word	0
	.word	-1
str_const75:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const1
	.byte	0	
	.align	2
	.word	-1
str_const74:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Main"
	.byte	0	
	.align	2
	.word	-1
str_const73:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Term"
	.byte	0	
	.align	2
	.word	-1
str_const72:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"App"
	.byte	0	
	.align	2
	.word	-1
str_const71:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"Lambda"
	.byte	0	
	.align	2
	.word	-1
str_const70:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const5
	.ascii	"Variable"
	.byte	0	
	.align	2
	.word	-1
str_const69:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Expr"
	.byte	0	
	.align	2
	.word	-1
str_const68:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"LambdaListRef"
	.byte	0	
	.align	2
	.word	-1
str_const67:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const7
	.ascii	"LambdaListNE"
	.byte	0	
	.align	2
	.word	-1
str_const66:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const8
	.ascii	"LambdaList"
	.byte	0	
	.align	2
	.word	-1
str_const65:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"VarListNE"
	.byte	0	
	.align	2
	.word	-1
str_const64:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"VarList"
	.byte	0	
	.align	2
	.word	-1
str_const63:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"String"
	.byte	0	
	.align	2
	.word	-1
str_const62:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Bool"
	.byte	0	
	.align	2
	.word	-1
str_const61:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"Int"
	.byte	0	
	.align	2
	.word	-1
str_const60:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"IO"
	.byte	0	
	.align	2
	.word	-1
str_const59:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"Object"
	.byte	0	
	.align	2
	.word	-1
str_const58:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const8
	.ascii	"_prim_slot"
	.byte	0	
	.align	2
	.word	-1
str_const57:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"SELF_TYPE"
	.byte	0	
	.align	2
	.word	-1
str_const56:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"_no_class"
	.byte	0	
	.align	2
	.word	-1
str_const55:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"<basic class>"
	.byte	0	
	.align	2
	.word	-1
str_const54:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"\n};\n};\n"
	.byte	0	
	.align	2
	.word	-1
str_const53:
	.word	12
	.word	11
	.word	String_dispTab
	.word	int_const12
	.ascii	"  main() : EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const52:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"class Main {\n"
	.byte	0	
	.align	2
	.word	-1
str_const51:
	.word	12
	.word	17
	.word	String_dispTab
	.word	int_const13
	.ascii	"(*Generated by lam.cl (Jeff Foster, March 2000)*)\n"
	.byte	0	
	.align	2
	.word	-1
str_const50:
	.word	12
	.word	16
	.word	String_dispTab
	.word	int_const14
	.ascii	"\n------------------cut here------------------\n"
	.byte	0	
	.align	2
	.word	-1
str_const49:
	.word	12
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	"Generating code for "
	.byte	0	
	.align	2
	.word	-1
str_const48:
	.word	12
	.word	20
	.word	String_dispTab
	.word	int_const16
	.ascii	"  apply(y : EvalObject) : EvalObject { { abort(); self; } };\n"
	.byte	0	
	.align	2
	.word	-1
str_const47:
	.word	12
	.word	19
	.word	String_dispTab
	.word	int_const17
	.ascii	"  init(p : Closure) : Closure {{ parent <- p; self; }};\n"
	.byte	0	
	.align	2
	.word	-1
str_const46:
	.word	12
	.word	12
	.word	String_dispTab
	.word	int_const18
	.ascii	"  get_x() : EvalObject { x };\n"
	.byte	0	
	.align	2
	.word	-1
str_const45:
	.word	12
	.word	14
	.word	String_dispTab
	.word	int_const19
	.ascii	"  get_parent() : Closure { parent };\n"
	.byte	0	
	.align	2
	.word	-1
str_const44:
	.word	12
	.word	9
	.word	String_dispTab
	.word	int_const20
	.ascii	"  x : EvalObject;\n"
	.byte	0	
	.align	2
	.word	-1
str_const43:
	.word	12
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	"  parent : Closure;\n"
	.byte	0	
	.align	2
	.word	-1
str_const42:
	.word	12
	.word	14
	.word	String_dispTab
	.word	int_const21
	.ascii	"class Closure inherits EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const41:
	.word	12
	.word	16
	.word	String_dispTab
	.word	int_const14
	.ascii	"  eval() : EvalObject { { abort(); self; } };\n"
	.byte	0	
	.align	2
	.word	-1
str_const40:
	.word	12
	.word	12
	.word	String_dispTab
	.word	int_const22
	.ascii	"class EvalObject inherits IO {\n"
	.byte	0	
	.align	2
	.word	-1
str_const39:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	" =>\n"
	.byte	0	
	.align	2
	.word	-1
str_const38:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"beta-reduce: "
	.byte	0	
	.align	2
	.word	-1
str_const37:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"z"
	.byte	0	
	.align	2
	.word	-1
str_const36:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"y"
	.byte	0	
	.align	2
	.word	-1
str_const35:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"x"
	.byte	0	
	.align	2
	.word	-1
str_const34:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"  esac)"
	.byte	0	
	.align	2
	.word	-1
str_const33:
	.word	12
	.word	17
	.word	String_dispTab
	.word	int_const23
	.ascii	"    o : Object => { abort(); new EvalObject; };\n"
	.byte	0	
	.align	2
	.word	-1
str_const32:
	.word	12
	.word	12
	.word	String_dispTab
	.word	int_const22
	.ascii	"    c : Closure => c.apply(y);\n"
	.byte	0	
	.align	2
	.word	-1
str_const31:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const7
	.ascii	"  case x of\n"
	.byte	0	
	.align	2
	.word	-1
str_const30:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	" in\n"
	.byte	0	
	.align	2
	.word	-1
str_const29:
	.word	12
	.word	10
	.word	String_dispTab
	.word	int_const24
	.ascii	"     y : EvalObject <- "
	.byte	0	
	.align	2
	.word	-1
str_const28:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	",\n"
	.byte	0	
	.align	2
	.word	-1
str_const27:
	.word	12
	.word	10
	.word	String_dispTab
	.word	int_const24
	.ascii	"(let x : EvalObject <- "
	.byte	0	
	.align	2
	.word	-1
str_const26:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"))"
	.byte	0	
	.align	2
	.word	-1
str_const25:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	")@("
	.byte	0	
	.align	2
	.word	-1
str_const24:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"(("
	.byte	0	
	.align	2
	.word	-1
str_const23:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"};\n"
	.byte	0	
	.align	2
	.word	-1
str_const22:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const25
	.ascii	";}};\n"
	.byte	0	
	.align	2
	.word	-1
str_const21:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const26
	.ascii	"      x <- y;\n"
	.byte	0	
	.align	2
	.word	-1
str_const20:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const4
	.byte	92
	.ascii	"n\");\n"
	.byte	0	
	.align	2
	.word	-1
str_const19:
	.word	12
	.word	13
	.word	String_dispTab
	.word	int_const27
	.ascii	"    { out_string(\"Applying closure "
	.byte	0	
	.align	2
	.word	-1
str_const18:
	.word	12
	.word	14
	.word	String_dispTab
	.word	int_const28
	.ascii	"  apply(y : EvalObject) : EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const17:
	.word	12
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	" inherits Closure {\n"
	.byte	0	
	.align	2
	.word	-1
str_const16:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"class Closure"
	.byte	0	
	.align	2
	.word	-1
str_const15:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"self))"
	.byte	0	
	.align	2
	.word	-1
str_const14:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"new Closure))"
	.byte	0	
	.align	2
	.word	-1
str_const13:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	").init("
	.byte	0	
	.align	2
	.word	-1
str_const12:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"((new Closure"
	.byte	0	
	.align	2
	.word	-1
str_const11:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"."
	.byte	0	
	.align	2
	.word	-1
str_const10:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.byte	92
	.byte	0	
	.align	2
	.word	-1
str_const9:
	.word	12
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"get_x()"
	.byte	0	
	.align	2
	.word	-1
str_const8:
	.word	12
	.word	11
	.word	String_dispTab
	.word	int_const29
	.ascii	"Error:  free occurrence of "
	.byte	0	
	.align	2
	.word	-1
str_const7:
	.word	12
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"get_parent()."
	.byte	0	
	.align	2
	.word	-1
str_const6:
	.word	12
	.word	16
	.word	String_dispTab
	.word	int_const30
	.ascii	"\nError: Expr is pure virtual; can't gen_code\n"
	.byte	0	
	.align	2
	.word	-1
str_const5:
	.word	12
	.word	16
	.word	String_dispTab
	.word	int_const31
	.ascii	"\nError: Expr is pure virtual; can't substitute\n"
	.byte	0	
	.align	2
	.word	-1
str_const4:
	.word	12
	.word	17
	.word	String_dispTab
	.word	int_const23
	.ascii	"\nError: Expr is pure virtual; can't beta-reduce\n"
	.byte	0	
	.align	2
	.word	-1
str_const3:
	.word	12
	.word	16
	.word	String_dispTab
	.word	int_const31
	.ascii	"\nError: Expr is pure virtual; can't print self\n"
	.byte	0	
	.align	2
	.word	-1
str_const2:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	" "
	.byte	0	
	.align	2
	.word	-1
str_const1:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"\n"
	.byte	0	
	.align	2
	.word	-1
str_const0:
	.word	12
	.word	7
	.word	String_dispTab
	.word	int_const32
	.ascii	"./lam-gc.cl"
	.byte	0	
	.align	2
	.word	-1
int_const32:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	11
	.word	-1
int_const31:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	47
	.word	-1
int_const30:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	45
	.word	-1
int_const29:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	27
	.word	-1
int_const28:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	39
	.word	-1
int_const27:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	35
	.word	-1
int_const26:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	14
	.word	-1
int_const25:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	5
	.word	-1
int_const24:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	23
	.word	-1
int_const23:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	48
	.word	-1
int_const22:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	31
	.word	-1
int_const21:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	36
	.word	-1
int_const20:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	18
	.word	-1
int_const19:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	37
	.word	-1
int_const18:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	30
	.word	-1
int_const17:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	56
	.word	-1
int_const16:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	61
	.word	-1
int_const15:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	20
	.word	-1
int_const14:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	46
	.word	-1
int_const13:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	50
	.word	-1
int_const12:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	24
	.word	-1
int_const11:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	2
	.word	-1
int_const10:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	7
	.word	-1
int_const9:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	9
	.word	-1
int_const8:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	10
	.word	-1
int_const7:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	12
	.word	-1
int_const6:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	13
	.word	-1
int_const5:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	8
	.word	-1
int_const4:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	6
	.word	-1
int_const3:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	3
	.word	-1
int_const2:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	4
	.word	-1
int_const1:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	0
	.word	-1
int_const0:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	1
	.word	-1
bool_const0:
	.word	11
	.word	4
	.word	Bool_dispTab
	.word	0
	.word	-1
bool_const1:
	.word	11
	.word	4
	.word	Bool_dispTab
	.word	1
class_nameTab:
	.word	str_const59
	.word	str_const60
	.word	str_const64
	.word	str_const65
	.word	str_const69
	.word	str_const70
	.word	str_const71
	.word	str_const72
	.word	str_const73
	.word	str_const74
	.word	str_const61
	.word	str_const62
	.word	str_const63
	.word	str_const66
	.word	str_const67
	.word	str_const68
class_objTab:
	.word	Object_protObj
	.word	Object_init
	.word	IO_protObj
	.word	IO_init
	.word	VarList_protObj
	.word	VarList_init
	.word	VarListNE_protObj
	.word	VarListNE_init
	.word	Expr_protObj
	.word	Expr_init
	.word	Variable_protObj
	.word	Variable_init
	.word	Lambda_protObj
	.word	Lambda_init
	.word	App_protObj
	.word	App_init
	.word	Term_protObj
	.word	Term_init
	.word	Main_protObj
	.word	Main_init
	.word	Int_protObj
	.word	Int_init
	.word	Bool_protObj
	.word	Bool_init
	.word	String_protObj
	.word	String_init
	.word	LambdaList_protObj
	.word	LambdaList_init
	.word	LambdaListNE_protObj
	.word	LambdaListNE_init
	.word	LambdaListRef_protObj
	.word	LambdaListRef_init
Main_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Term.var
	.word	Term.lam
	.word	Term.app
	.word	Term.i
	.word	Term.k
	.word	Term.s
	.word	Main.beta_reduce
	.word	Main.eval_class
	.word	Main.closure_class
	.word	Main.gen_code
	.word	Main.main
Term_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Term.var
	.word	Term.lam
	.word	Term.app
	.word	Term.i
	.word	Term.k
	.word	Term.s
App_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	App.print_self
	.word	App.beta
	.word	App.substitute
	.word	App.gen_code
	.word	App.init
Lambda_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Lambda.print_self
	.word	Lambda.beta
	.word	Lambda.substitute
	.word	Lambda.gen_code
	.word	Lambda.init
	.word	Lambda.apply
	.word	Lambda.gen_closure_code
Variable_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Variable.print_self
	.word	Variable.beta
	.word	Variable.substitute
	.word	Variable.gen_code
	.word	Variable.init
Expr_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Expr.print_self
	.word	Expr.beta
	.word	Expr.substitute
	.word	Expr.gen_code
LambdaListRef_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaListRef.isNil
	.word	LambdaListRef.headE
	.word	LambdaListRef.headC
	.word	LambdaListRef.headN
	.word	LambdaListRef.reset
	.word	LambdaListRef.add
	.word	LambdaListRef.removeHead
LambdaListNE_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaListNE.isNil
	.word	LambdaListNE.headE
	.word	LambdaListNE.headC
	.word	LambdaListNE.headN
	.word	LambdaListNE.tail
	.word	LambdaList.add
	.word	LambdaListNE.init
LambdaList_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaList.isNil
	.word	LambdaList.headE
	.word	LambdaList.headC
	.word	LambdaList.headN
	.word	LambdaList.tail
	.word	LambdaList.add
VarListNE_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	VarListNE.isNil
	.word	VarListNE.head
	.word	VarListNE.tail
	.word	VarList.add
	.word	VarListNE.print
	.word	VarListNE.init
VarList_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	VarList.isNil
	.word	VarList.head
	.word	VarList.tail
	.word	VarList.add
	.word	VarList.print
String_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	String.length
	.word	String.concat
	.word	String.substr
Bool_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
Int_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
IO_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
Object_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	-1
Main_protObj:
	.word	9
	.word	3
	.word	Main_dispTab
	.word	-1
Term_protObj:
	.word	8
	.word	3
	.word	Term_dispTab
	.word	-1
App_protObj:
	.word	7
	.word	5
	.word	App_dispTab
	.word	0
	.word	0
	.word	-1
Lambda_protObj:
	.word	6
	.word	5
	.word	Lambda_dispTab
	.word	0
	.word	0
	.word	-1
Variable_protObj:
	.word	5
	.word	4
	.word	Variable_dispTab
	.word	str_const75
	.word	-1
Expr_protObj:
	.word	4
	.word	3
	.word	Expr_dispTab
	.word	-1
LambdaListRef_protObj:
	.word	15
	.word	5
	.word	LambdaListRef_dispTab
	.word	int_const1
	.word	0
	.word	-1
LambdaListNE_protObj:
	.word	14
	.word	7
	.word	LambdaListNE_dispTab
	.word	0
	.word	int_const1
	.word	0
	.word	0
	.word	-1
LambdaList_protObj:
	.word	13
	.word	3
	.word	LambdaList_dispTab
	.word	-1
VarListNE_protObj:
	.word	3
	.word	5
	.word	VarListNE_dispTab
	.word	0
	.word	0
	.word	-1
VarList_protObj:
	.word	2
	.word	3
	.word	VarList_dispTab
	.word	-1
String_protObj:
	.word	12
	.word	5
	.word	String_dispTab
	.word	int_const1
	.word	0
	.word	-1
Bool_protObj:
	.word	11
	.word	4
	.word	Bool_dispTab
	.word	0
	.word	-1
Int_protObj:
	.word	10
	.word	4
	.word	Int_dispTab
	.word	0
	.word	-1
IO_protObj:
	.word	1
	.word	3
	.word	IO_dispTab
	.word	-1
Object_protObj:
	.word	0
	.word	3
	.word	Object_dispTab
	.globl	heap_start
heap_start:
	.word	0
	.text
	.globl	Main_init
	.globl	Int_init
	.globl	String_init
	.globl	Bool_init
	.globl	Main.main
Main_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Term_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Main.beta_reduce:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const38
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label0
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label0:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 4($fp)
	bne	$a0 $zero label1
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label1:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 bool_const0
	sw	$a0 0($fp)
	move	$a0 $zero
	sw	$a0 -4($fp)
label2:
	lw	$a0 0($fp)
	lw	$t1 12($a0)
	la	$a0 bool_const1
	beqz	$t1 label4
	la	$a0 bool_const0
label4:
	lw	$a0 12($a0)
	beqz	$a0 label3
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 4($fp)
	bne	$a0 $zero label5
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label5:
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	lw	$a0 -4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$t1 4($sp)
	addiu	$sp $sp 4
	move	$t2 $a0
	la	$a0 bool_const1
	beq	$t1 $t2 label9
	la	$a1 bool_const0
	jal	equality_test
label9:
	lw	$a0 12($a0)
	bne	$a0 $zero label6
label7:
	lw	$a0 -4($fp)
	sw	$a0 4($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const39
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label10
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label10:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 4($fp)
	bne	$a0 $zero label11
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label11:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label8
label6:
	la	$a0 bool_const1
	sw	$a0 0($fp)
label8:
	b	label2
label3:
	move	$a0 $zero
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label12
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label12:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$a0 4($fp)
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Main.eval_class:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const40
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label13
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label13:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const41
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label14
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label14:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const23
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label15
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label15:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Main.closure_class:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const42
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label16
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label16:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const43
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label17
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label17:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const44
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label18
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label18:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const45
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label19
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label19:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const46
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label20
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label20:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const47
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label21
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label21:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const48
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label22
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label22:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const23
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label23
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label23:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Main.gen_code:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -16
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	la	$a0 LambdaListRef_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	LambdaListRef_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	bne	$a0 $zero label24
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label24:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const49
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label25
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label25:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 4($fp)
	bne	$a0 $zero label26
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label26:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const50
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label27
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label27:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const51
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label28
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label28:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label29
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label29:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 56($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label30
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label30:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 60($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const52
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label31
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label31:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const53
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label32
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label32:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	la	$a0 VarList_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	VarList_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 8($sp)
	lw	$a0 0($fp)
	sw	$a0 4($sp)
	lw	$a0 4($fp)
	bne	$a0 $zero label33
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label33:
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const54
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label34
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label34:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
label35:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label38
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label38:
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$t1 12($a0)
	la	$a0 bool_const1
	beqz	$t1 label37
	la	$a0 bool_const0
label37:
	lw	$a0 12($a0)
	beqz	$a0 label36
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label39
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label39:
	lw	$t1 8($a0)
	lw	$t1 16($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label40
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label40:
	lw	$t1 8($a0)
	lw	$t1 20($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -8($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label41
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label41:
	lw	$t1 8($a0)
	lw	$t1 24($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -12($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label42
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label42:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -12
	lw	$a0 -12($fp)
	sw	$a0 12($sp)
	lw	$a0 -4($fp)
	sw	$a0 8($sp)
	lw	$a0 0($fp)
	sw	$a0 4($sp)
	lw	$a0 -8($fp)
	bne	$a0 $zero label43
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label43:
	lw	$t1 8($a0)
	lw	$t1 52($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label35
label36:
	move	$a0 $zero
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const50
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label44
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label44:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 24
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Main.main:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label46
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label46:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	bne	$a0 $zero label45
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label45:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label47
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label47:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label49
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label49:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	bne	$a0 $zero label48
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label48:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label50
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label50:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label52
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label52:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	bne	$a0 $zero label51
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label51:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label53
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label53:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label58
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label58:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label59
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label59:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label57
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label57:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label60
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label60:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label56
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label56:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label61
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label61:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label55
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label55:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label54
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label54:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 52($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label65
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label65:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label66
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label66:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label64
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label64:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label67
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label67:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label63
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label63:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label62
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label62:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 52($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label70
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label70:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label71
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label71:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label69
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label69:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label68
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label68:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 64($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label76
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label76:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label77
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label77:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label75
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label75:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label78
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label78:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label74
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label74:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label79
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label79:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label73
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label73:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label72
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label72:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 64($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label89
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label89:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label90
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label90:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label88
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label88:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label91
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label91:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label87
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label87:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label92
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label92:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label86
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label86:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label93
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label93:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label85
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label85:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label94
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label94:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label84
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label84:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label95
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label95:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label83
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label83:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label96
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label96:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label82
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label82:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label97
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label97:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label81
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label81:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label80
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label80:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 64($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label101
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label101:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label103
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label103:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label104
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label104:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label102
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label102:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label100
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label100:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label106
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label106:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label108
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label108:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label109
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label109:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label107
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label107:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label105
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label105:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label99
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label99:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label98
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label98:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 64($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 int_const1
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	IO_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Term.var:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 Variable_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	Variable_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 0($fp)
	bne	$a0 $zero label110
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label110:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term.lam:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 Lambda_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	Lambda_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 0($fp)
	bne	$a0 $zero label111
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label111:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term.app:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 App_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	App_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 0($fp)
	bne	$a0 $zero label112
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label112:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term.i:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const35
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label113
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label113:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 0($fp)
	sw	$a0 8($sp)
	lw	$a0 0($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label114
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label114:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term.k:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const35
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label115
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label115:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const36
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label116
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label116:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 0($fp)
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 -4($fp)
	sw	$a0 8($sp)
	lw	$a0 0($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label118
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label118:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label117
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label117:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Term.s:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -12
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const35
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label119
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label119:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const36
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label120
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label120:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const37
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label121
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label121:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -8($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 0($fp)
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 -4($fp)
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 -8($fp)
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 0($fp)
	sw	$a0 8($sp)
	lw	$a0 -8($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label126
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label126:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 -4($fp)
	sw	$a0 8($sp)
	lw	$a0 -8($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label127
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label127:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label125
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label125:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label124
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label124:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label123
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label123:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label122
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label122:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
App_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Expr_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
App.init:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
App.print_self:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const24
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label128
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label128:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 12($s0)
	bne	$a0 $zero label129
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label129:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const25
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label130
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label130:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label131
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label131:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const26
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label132
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label132:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
App.beta:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -12
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 0($fp)
	beqz	$a0 label135
	li	$t5 -1
	la	$t6 label133
label137:
	lw	$t1 0($a0)
	li	$t2 6
	beq	$t1 $t2 label138
	blt	$t1 6 label139
	bgt	$t1 6 label139
	bgt	$t5 6 label139
	li	$t5 6
	la	$t6 label138
	b	label139
label138:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 16($s0)
	sw	$a0 4($sp)
	lw	$a0 0($fp)
	bne	$a0 $zero label141
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label141:
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label136
label139:
	lw	$t1 0($a0)
	li	$t2 4
	beq	$t1 $t2 label140
	blt	$t1 4 label134
	bgt	$t1 7 label134
	bgt	$t5 4 label134
	li	$t5 4
	b	label140
label140:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 12($s0)
	bne	$a0 $zero label142
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label142:
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	la	$a0 App_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	App_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 -8($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 -4($fp)
	sw	$a0 8($sp)
	lw	$a0 16($s0)
	sw	$a0 4($sp)
	lw	$a0 -8($fp)
	bne	$a0 $zero label143
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label143:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label136
label134:
	jalr		$t6
label135:
	la	$a0 str_const0
	li	$t1 1
	jal	_case_abort2
label133:
	move	$a0 $s0
	jal	_case_abort
label136:
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
App.substitute:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -12
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 12($s0)
	bne	$a0 $zero label144
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label144:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label145
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label145:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 -4($fp)
	la	$a0 App_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	App_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 -8($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 0($fp)
	sw	$a0 8($sp)
	lw	$a0 -4($fp)
	sw	$a0 4($sp)
	lw	$a0 -8($fp)
	bne	$a0 $zero label146
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label146:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 24
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
App.gen_code:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const27
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label147
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label147:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 12($s0)
	bne	$a0 $zero label148
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label148:
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const28
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label149
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label149:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const29
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label150
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label150:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label151
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label151:
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const30
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label152
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label152:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const31
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label153
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label153:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const32
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label154
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label154:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const33
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label155
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label155:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const34
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label156
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label156:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Expr_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Lambda.init:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.print_self:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const10
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label157
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label157:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 12($s0)
	bne	$a0 $zero label158
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label158:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const11
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label159
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label159:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label160
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label160:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.beta:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.apply:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 12($s0)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label161
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label161:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.substitute:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	lw	$t1 4($sp)
	addiu	$sp $sp 4
	move	$t2 $a0
	la	$a0 bool_const1
	beq	$t1 $t2 label165
	la	$a1 bool_const0
	jal	equality_test
label165:
	lw	$a0 12($a0)
	bne	$a0 $zero label162
label163:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label166
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label166:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	la	$a0 Lambda_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	Lambda_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	sw	$a0 -4($fp)
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 12($s0)
	sw	$a0 8($sp)
	lw	$a0 0($fp)
	sw	$a0 4($sp)
	lw	$a0 -4($fp)
	bne	$a0 $zero label167
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label167:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label164
label162:
	move	$a0 $s0
label164:
	lw	$ra 4($sp)
	addiu	$sp $sp 20
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.gen_code:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const12
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label168
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label168:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 8($fp)
	sw	$a0 8($sp)
	move	$a0 $s0
	sw	$a0 4($sp)
	lw	$a0 4($fp)
	bne	$a0 $zero label170
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label170:
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label169
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label169:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 16($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const13
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label171
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label171:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 8($fp)
	bne	$a0 $zero label175
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label175:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$a0 12($a0)
	bne	$a0 $zero label172
label173:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const15
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label176
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label176:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label174
label172:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const14
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label177
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label177:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
label174:
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Lambda.gen_closure_code:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const16
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label178
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label178:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 12($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label179
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label179:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 16($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const17
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label180
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label180:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const18
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label181
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label181:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const19
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label182
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label182:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 12($fp)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label183
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label183:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 16($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const20
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label184
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label184:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const21
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label185
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label185:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 4($sp)
	lw	$a0 8($fp)
	bne	$a0 $zero label187
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label187:
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 8($sp)
	lw	$a0 4($fp)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label186
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label186:
	lw	$t1 8($a0)
	lw	$t1 40($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const22
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label188
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label188:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const23
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label189
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label189:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Variable_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Expr_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Variable.init:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Variable.print_self:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label190
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label190:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Variable.beta:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Variable.substitute:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	move	$a0 $s0
	lw	$t1 4($sp)
	addiu	$sp $sp 4
	move	$t2 $a0
	la	$a0 bool_const1
	beq	$t1 $t2 label194
	la	$a1 bool_const0
	jal	equality_test
label194:
	lw	$a0 12($a0)
	bne	$a0 $zero label191
label192:
	move	$a0 $s0
	b	label193
label191:
	lw	$a0 4($fp)
label193:
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Variable.gen_code:
	move	$fp $sp
	move	$s0 $a0
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	sw	$a0 0($fp)
label195:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label200
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label200:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$a0 12($a0)
	bne	$a0 $zero label197
label198:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label203
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label203:
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	move	$a0 $s0
	lw	$t1 4($sp)
	addiu	$sp $sp 4
	move	$t2 $a0
	la	$a0 bool_const1
	beq	$t1 $t2 label202
	la	$a1 bool_const0
	jal	equality_test
label202:
	lw	$t1 12($a0)
	la	$a0 bool_const1
	beqz	$t1 label201
	la	$a0 bool_const0
label201:
	b	label199
label197:
	la	$a0 bool_const0
label199:
	lw	$a0 12($a0)
	beqz	$a0 label196
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const7
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label204
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label204:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label205
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label205:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$a0 0($fp)
	b	label195
label196:
	move	$a0 $zero
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 0($fp)
	bne	$a0 $zero label209
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label209:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$a0 12($a0)
	bne	$a0 $zero label206
label207:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const9
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label210
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label210:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	b	label208
label206:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const8
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label211
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label211:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label212
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label212:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label213
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label213:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label214
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label214:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
label208:
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Expr_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	IO_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Expr.print_self:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const3
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label215
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label215:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label216
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label216:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Expr.beta:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const4
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label217
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label217:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label218
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label218:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Expr.substitute:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const5
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label219
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label219:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label220
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label220:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
Expr.gen_code:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const6
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label221
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label221:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label222
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label222:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	la	$a0 int_const1
	sw	$a0 12($s0)
	move	$a0 $s0
	jal	Object_init
	la	$a0 int_const1
	sw	$a0 12($s0)
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.isNil:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label223
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label223:
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.headE:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label224
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label224:
	lw	$t1 8($a0)
	lw	$t1 16($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.headC:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label225
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label225:
	lw	$t1 8($a0)
	lw	$t1 20($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.headN:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label226
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label226:
	lw	$t1 8($a0)
	lw	$t1 24($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.reset:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	la	$a0 int_const1
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	la	$a0 LambdaList_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	LambdaList_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.add:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -12
	lw	$a0 8($fp)
	sw	$a0 12($sp)
	lw	$a0 4($fp)
	sw	$a0 8($sp)
	lw	$a0 12($s0)
	sw	$a0 4($sp)
	lw	$a0 16($s0)
	bne	$a0 $zero label227
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label227:
	lw	$t1 8($a0)
	lw	$t1 32($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 int_const0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($sp)
	jal	Object.copy
	lw	$t1 12($a0)
	lw	$t2 4($sp)
	lw	$t2 12($t2)
	add	$t1 $t1 $t2
	sw	$t1 12($a0)
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 int_const0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($sp)
	jal	Object.copy
	lw	$t1 12($a0)
	lw	$t2 4($sp)
	lw	$t2 12($t2)
	sub	$t1 $t1 $t2
	sw	$t1 12($a0)
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListRef.removeHead:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label228
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label228:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	LambdaList_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.isNil:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 bool_const0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE.headE:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 20($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE.headC:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE.headN:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE.tail:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 24($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaListNE.init:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($fp)
	lw	$s0 4($sp)
	sw	$a0 20($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($fp)
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$s0 4($sp)
	sw	$a0 24($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 20
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Object_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.isNil:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 bool_const1
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList.headE:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label229
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label229:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 VarList_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	VarList_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList.headC:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label230
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label230:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 Lambda_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	Lambda_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList.headN:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label231
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label231:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 int_const1
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList.tail:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label232
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label232:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 LambdaList_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	LambdaList_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
LambdaList.add:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -16
	lw	$a0 12($fp)
	sw	$a0 16($sp)
	lw	$a0 8($fp)
	sw	$a0 12($sp)
	lw	$a0 4($fp)
	sw	$a0 8($sp)
	move	$a0 $s0
	sw	$a0 4($sp)
	la	$a0 LambdaListNE_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	LambdaListNE_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	bne	$a0 $zero label233
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label233:
	lw	$t1 8($a0)
	lw	$t1 36($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 16
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarListNE_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	VarList_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
VarListNE.isNil:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 bool_const0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarListNE.head:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarListNE.tail:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarListNE.init:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 8($fp)
	lw	$s0 4($sp)
	sw	$a0 12($s0)
	addiu	$sp $sp 4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	lw	$s0 4($sp)
	sw	$a0 16($s0)
	addiu	$sp $sp 4
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 12
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarListNE.print:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 12($s0)
	bne	$a0 $zero label234
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label234:
	lw	$t1 8($a0)
	lw	$t1 28($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const2
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label235
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label235:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	lw	$a0 16($s0)
	bne	$a0 $zero label236
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label236:
	lw	$t1 8($a0)
	lw	$t1 44($t1)
	jalr		$t1
	addiu	$sp $sp 8
	move	$a0 $s0
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarList_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	IO_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
VarList.isNil:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	la	$a0 bool_const1
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarList.head:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label237
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label237:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 Variable_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	Variable_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarList.tail:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp 0
	move	$a0 $s0
	bne	$a0 $zero label238
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label238:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 0($t1)
	jalr		$t1
	addiu	$sp $sp 8
	la	$a0 VarList_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	VarList_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarList.add:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -8
	lw	$a0 4($fp)
	sw	$a0 8($sp)
	move	$a0 $s0
	sw	$a0 4($sp)
	la	$a0 VarListNE_protObj
	jal	Object.copy
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	jal	VarListNE_init
	lw	$a0 4($sp)
	addiu	$sp $sp 4
	bne	$a0 $zero label239
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label239:
	lw	$t1 8($a0)
	lw	$t1 48($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 8
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
VarList.print:
	move	$fp $sp
	move	$s0 $a0
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	addiu	$sp $sp -4
	la	$a0 str_const1
	sw	$a0 4($sp)
	move	$a0 $s0
	bne	$a0 $zero label240
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label240:
	move	$a0 $s0
	lw	$t1 8($a0)
	lw	$t1 12($t1)
	jalr		$t1
	addiu	$sp $sp 8
	lw	$ra 4($sp)
	addiu	$sp $sp 4
	lw	$s0 4($sp)
	lw	$fp 8($sp)
	jr	$ra	
String_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Object_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Bool_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Object_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Int_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Object_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
IO_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	jal	Object_init
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Object_init:
	addiu	$sp $sp -12
	sw	$fp 12($sp)
	sw	$s0 8($sp)
	sw	$ra 4($sp)
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	move	$a0 $s0
	lw	$ra 4($sp)
	lw	$s0 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	

# end of generated code
